- hosts: all
  vars_files:
    - vars/vars.yml
  
  tasks:
  - name: Install IIS Web-Server with sub features and management tools
    win_feature:
      name: Web-WebServer
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: win_feature

  - name: Install IIS Ftp-Server with sub features and management tools
    win_feature:
      name: Web-Ftp-Server
      state: present
      include_sub_features: yes
      include_management_tools: yes
    when: ftp  
    register: win_feature
  
  - name: Configure Pool
    win_iis_webapppool:
      name: "{{poolname}}"
      state: "{{poolstate}}"
      attributes:
        managedPipelineMode: "{{poolpipeline_mode}}"
        processModel.identityType: SpecificUser
        processModel.userName: "{{poolservice_user}}"
        processModel.password: "{{poolservice_password}}"
        processModel.loadUserProfile: True
        managedRuntimeVersion: "{{poolmanagedRuntime_version}}"
        autoStart: "{{poolautostart}}"
 
  - name: Remove default IIS site
    win_iis_website:
      name: Default Web Site
      state: absent
    when: not defaultsite
      
  - name: Remove previous IIS site
    win_iis_website:
      name: "{{sitename}}"
      state: absent

  - name: Configure Site
    win_iis_website:
      name: "{{sitename}}"
      state: "{{sitestate}}"
      # port: "{{siteport}}"
      # ip: "{{siteip}}"
      application_pool: "{{sitepool}}"
      physical_path: "{{sitepath}}"
      # ssl: "{{sitessl}}"
      parameters: "logfile.directory:{{sitelogdir}}"
    ignore_errors: yes
    register: website

  - name: Configure Bindings
    win_iis_webbinding:
      name: "{{sitename}}"
      protocol: "{{bindprotocol}}"
      port: "{{bindport}}"
      ip: "{{bindip}}"
      host_header: "{{bindheader}}"
      certificate_hash: "{{bindcerthash}}"
      ssl_flags:  "{{bindflag}}"
      state: "{{bindstate}}"
