---
- name: Check if self-signed ssl certificat exist
  win_shell: dir cert:\LocalMachine\My -Recurse | where {$_.subject -eq "cn={{webbindheader}}"}
  register: wingetcert_result
  when: webbindprotocol == "https"

- name: Create self-signed ssl certificat if needed
  win_shell: New-SelfSignedCertificate -DnsName {{webbindheader}} -CertStoreLocation cert:\LocalMachine\My
  register: wincreatecert_result
  when: webbindprotocol == "https" and not wingetcert_result.stdout

- name: Configure Bindings with existing auto certificate
  win_iis_webbinding:
    name: "{{websitename}}"
    protocol: "{{webbindprotocol}}"
    port: "{{webbindport}}"
    ip: "{{webbindip}}"
    host_header: "{{webbindheader}}"
    certificate_hash: "{{wingetcert_result.stdout.split()[7]}}"
    ssl_flags:  "{{webbindflag}}"
    state: "{{webbindstate}}"
  when: wingetcert_result.stdout

- name: Configure Bindings with new auto certificate
  win_iis_webbinding:
    name: "{{websitename}}"
    protocol: "{{webbindprotocol}}"
    port: "{{webbindport}}"
    ip: "{{webbindip}}"
    host_header: "{{webbindheader}}"
    certificate_hash: "{{wincreatecert_result.stdout.split()[7]}}"
    ssl_flags:  "{{webbindflag}}"
    state: "{{webbindstate}}"
  when: not wingetcert_result.stdout
