---
- name: Configure Bindings
  win_iis_webbinding:
    name: "{{websitename}}"
    protocol: "{{webbindprotocol}}"
    port: "{{webbindport}}"
    ip: "{{webbindip}}"
    host_header: "{{webbindheader}}"
    certificate_hash: "{{webbindcerthash}}"
    ssl_flags:  "{{webbindflag}}"
    state: "{{webbindstate}}"
