---
- name: check mandatory inputs are present
  assert:
    that:
      win_user_name is defined
      win_account_user_password is defined
      webpoolname is defined
      webpoolname | lenght > 0

- name: Configure Pool
  win_iis_webapppool:
    name: "{{webpoolname}}"
    state: "{{webpoolstate}}"
    attributes:
      managedPipelineMode: "{{webpoolpipeline_mode}}"
      processModel.identityType: SpecificUser
      processModel.userName: "{{win_user_name}}"
      processModel.password: "{{win_account_user_password}}"
      processModel.loadUserProfile: True
      managedRuntimeVersion: "{{webpoolmanagedRuntime_version}}"
      autoStart: "{{webpoolautostart}}"
