---
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-WebServer
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Install IIS Ftp-Server with sub features and management tools
  win_feature:
    name: Web-Ftp-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  when: webinstallftp
