---
- name: Remove default IIS site
  win_iis_website:
    name: Default Web Site
    state: absent
  when: not websitedefault

- name: Create directory structure
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{websitepath}}"
    - "{{websitelogdir}}"
      
- name: Configure Site
  win_iis_website:
    name: "{{websitename}}"
    state: "{{websitestate}}"
    port: "{{websiteport}}"
    ip: "{{websiteip}}"
    application_pool: "{{websitepool}}"
    physical_path: "{{websitepath}}"
    ssl: "{{websitessl}}"
    parameters: "logfile.directory:{{websitelogdir}}"
    register: website
